// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfessorMewData.Contexts;

namespace ProfessorMewData.Migrations
{
    [DbContext(typeof(RaidContext))]
    [Migration("20210315123055_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("ProfessorMewData.Models.Raid.RaidBench", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<int>("DPS")
                        .HasColumnType("int");

                    b.Property<long>("GuildID")
                        .HasColumnType("bigint");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<double>("Scale")
                        .HasColumnType("double");

                    b.Property<int>("Specialization")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GuildID");

                    b.ToTable("RaidBenches");
                });

            modelBuilder.Entity("ProfessorMewData.Models.Raid.RaidGuild", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("DBDiscordID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("ProfessorMewData.Models.Raid.RaidLink", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("GuildID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("GuildID");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("ProfessorMewData.Models.Raid.RaidRecord", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasDefaultValue("None");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<int>("DPS")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Specialization")
                        .HasColumnType("int");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("ProfessorMewData.Models.Raid.RaidUser", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasDefaultValue("None");

                    b.Property<string>("DBDiscordID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("GuildID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("GuildID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProfessorMewData.Models.Raid.RaidBench", b =>
                {
                    b.HasOne("ProfessorMewData.Models.Raid.RaidGuild", "Guild")
                        .WithMany("Benches")
                        .HasForeignKey("GuildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("ProfessorMewData.Models.Raid.RaidLink", b =>
                {
                    b.HasOne("ProfessorMewData.Models.Raid.RaidGuild", "Guild")
                        .WithMany("Links")
                        .HasForeignKey("GuildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("ProfessorMewData.Models.Raid.RaidRecord", b =>
                {
                    b.HasOne("ProfessorMewData.Models.Raid.RaidUser", "User")
                        .WithMany("Records")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProfessorMewData.Models.Raid.RaidUser", b =>
                {
                    b.HasOne("ProfessorMewData.Models.Raid.RaidGuild", "Guild")
                        .WithMany("Users")
                        .HasForeignKey("GuildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("ProfessorMewData.Models.Raid.RaidGuild", b =>
                {
                    b.Navigation("Benches");

                    b.Navigation("Links");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProfessorMewData.Models.Raid.RaidUser", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
